### PR TITLE
Fix test set evaluation GPU memory leak

### PR DESCRIPTION
**Pull request by dblasko**
Hi,

As I have been reproducing your results based on your codebase, I have noticed that the test-set evaluation script (`src/full_model/test_set_evaluation.py`) has a GPU memory leak. As it iterates through batches for the language model evaluation, GPU memory use keeps climbing from batch to batch. On my hardware, that led to out-of-memory errors at some later point in evaluation, even with a batch size of 1 whereas that was no problem at training.

I've tracked the source of the leak down, and it seems that re-initiating the `bertscore` evaluation module for each batch (as `get_generated_reports` is called inside the dataset iterator loop, and `evaluate.load("bertscore")` is called in the function) was what caused this behavior. 

By initiating the evaluation module once before the loop, and keeping it on GPU throughout the dataset iteration as done in my suggested modifications, the memory leak was resolved and larger batches could be used with stable GPU memory usage. 

Thank you for the excellent and very well documented work!

### CODE REVIEW

**Comment by ttanida** [comment]
Hi Daniel,

thank you very much for your PR!

You are right, it does make much more sense to initialize the bertscore object once at the very beginning of the loop.
That was a great find, thanks again!

Best,
Tim

**Review by jianfeixu95 — COMMENTED** [review]
after this merge was completed, the code is fully wrong at line 344-354

**Comment by ttanida** [comment]
@jianfeixu95, what exactly is wrong?

**Comment by jianfeixu95** [comment]
1. The latest version of `test_set_evaluation.py` downloaded from the repository has issues with its code structure, which prevents it from running properly.
https://github.com/ttanida/rgrg/blob/main/src/full_model/test_set_evaluation.py

CleanShot 2024-06-22 at 18 11 05@2x

2. Additionally, when using the `get_generated_reports` function in the `evaluate_language_model.py` file, the `bert_score` parameter is missing.
https://github.com/ttanida/rgrg/blob/main/src/full_model/evaluate_full_model/evaluate_language_model.py

CleanShot 2024-06-22 at 18 16 38@2x

From: Tim Tanida ***@***.***>
Date: Friday, June 21, 2024 at 18:06
To: ttanida/rgrg ***@***.***>
Cc: Jianfei Xu ***@***.***>, Mention ***@***.***>
Subject: Re: [ttanida/rgrg] Fix test set evaluation GPU memory leak (PR #27)

@jianfeixu95<https://github.com/jianfeixu95>, what exactly is wrong?

**Comment by ttanida** [comment]
Hello @jianfeixu95,

thanks for bringing this to my attention, there were indeed some errors in the code after the PR.
I fixed them now with the latest commit: https://github.com/ttanida/rgrg/commit/9520b6d7f555d458898c6795e57cc00f7f90182b

Best,
Tim

**Pull request merged**
